### ISSUE TITLE
Did it work on1.27?

### ISSUE THREAD

**Issue by q531620267** [lep/jhcr#2]
Hello, can I use jhcr in war3 version 1.27? I try according to your method, and when the map is running, I can't save the map. How do I do it when the map is running: "after we add the" something ", we again save the map and run the" 1-run-after-save-map-before-game-is-running.bat "

**Comment by lep** [comment]
I don't know what bat scripts you are using. There might be some problems if I use natives which didn't exist yet in 1.27. Best way is to run pjass over the generated scripts which should probably be easy to integrate into your bat scripts.
If your willing we could probably make it work on your patch but it would need some back and forth.

Am 27. Oktober 2021 02:24:08 MESZ schrieb q531620267 ***@***.***>:

**Comment by q531620267** [comment]
> I don't know what bat scripts you are using. There might be some problems if I use natives which didn't exist yet in 1.27. Best way is to run pjass over the generated scripts which should probably be easy to integrate into your bat scripts. If your willing we could probably make it work on your patch but it would need some back and forth. Am 27. Oktober 2021 02:24:08 MESZ schrieb q531620267 ***@***.***>:
> […](#)
> Hello, can I use jhcr in war3 version 1.27? I try according to your method, and when the map is running, I can't save the map. How do I do it when the map is running: "after we add the" something ", we again save the map and run the" 1-run-after-save-map-before-game-is-running.bat " -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #2

https://www.hiveworkshop.com/threads/jass-hot-code-reload.313811/post-3339166  I do it this way

**Comment by q531620267** [comment]
Can you make a 1.27 version and use the jhcr video of GUI? I am willing to pay a certain reward for this, because I have studied for a day and got nothing ：(

**Comment by q531620267** [comment]
Hello. did 1.27 version can work no JHCR? now i use wurst script to make war3 map,but it takes a long time to test the map every time . i don't know how to use pjass.i always use GUI to make maps. thank you for answer.
wurst script:
jhcr.exe: compiled.j.txt: hGetContents: invalid argument (invalid byte sequence) i use jhcr-1.32.9

**Comment by lep** [comment]
Since commit 6456c62a5c15ce4044a076905345bcfd27df297e we have a working version for older patches. There are probably still bugs lurking but the ground work is done.
